-- ============================================================================
-- SEED de fotos: crea los 15 productos de la campana con sus 5 fotos cada uno.
-- Pegar en Supabase -> SQL Editor -> Run.
--
-- SEGURO:
--   * NO duplica: si ya existe un producto con el mismo nombre, lo saltea.
--   * Entra con precio 0 y activo=false (OCULTO) para que NO salga en la tienda
--     con precio equivocado. Despues, en el admin (o con un UPDATE), poné el
--     precio real y tildá "Visible en la tienda".
--   * No toca ningun producto ya existente.
--
-- Despues de correrlo, para publicar cada uno: en admin.html -> Tienda ->
-- editar producto -> poner Precio -> tildar "Visible en la tienda".
-- ============================================================================

insert into productos (nombre, descripcion, categoria, colores, talles, imagenes, slug, orden, moneda, precio, activo, destacado)
select v.nombre, v.descripcion, v.categoria, v.colores, v.talles, v.imagenes, v.slug, v.orden, 'ARS', 0, false, false
from (values
  ('Bomber de cuero verde oliva', 'Bomber de cuero genuino en verde oliva, de silueta oversize y caida relajada. Punos y ruedo elastizados, cierre metalico y una impronta urbana que combina con todo. Hecha a mano para durar.', 'Camperas', ARRAY['Verde oliva']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/bomber/bomber-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/bomber/bomber-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/bomber/bomber-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/bomber/bomber-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/bomber/bomber-5.jpg']::text[], 'bomber', 1),
  ('Trench largo de cuero', 'Trench largo de cuero negro, sobrio y elegante. Cae impecable y se usa abierto o cerrado con cinturon. Una pieza statement para el entretiempo y el frio.', 'Tapados', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/trench/trench-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/trench/trench-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/trench/trench-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/trench/trench-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/trench/trench-5.jpg']::text[], 'trench', 2),
  ('Campera Napalan (aviador)', 'Campera aviadora de cuero negro con cuello y forro de corderito camel. Abriga de verdad y tiene la actitud de un clasico atemporal.', 'Camperas', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-napalan/campera-napalan-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-napalan/campera-napalan-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-napalan/campera-napalan-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-napalan/campera-napalan-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-napalan/campera-napalan-5.jpg']::text[], 'campera-napalan', 3),
  ('Tapado Napalan largo (reversible)', 'Tapado largo de napa reversible: cuero caramelo de un lado, corderito crudo del otro. Maximo abrigo, dos prendas en una.', 'Tapados', ARRAY['Caramelo']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-largo/napalan-largo-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-largo/napalan-largo-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-largo/napalan-largo-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-largo/napalan-largo-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-largo/napalan-largo-5.jpg']::text[], 'napalan-largo', 4),
  ('Tapado Napalan 3/4 (reversible)', 'Tapado 3/4 reversible en cuero negro y corderito, con cuello sport amplio y calce envolvente. Ideal para los dias mas frios.', 'Tapados', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-3-4/napalan-3-4-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-3-4/napalan-3-4-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-3-4/napalan-3-4-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-3-4/napalan-3-4-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/napalan-3-4/napalan-3-4-5.jpg']::text[], 'napalan-3-4', 5),
  ('Campera de cuero corte trucker', 'Campera de cuero marron con corte trucker (estilo campera de jean): canesu, bolsillos con tapa y un calce boxy que la vuelve un basico de fondo de placard.', 'Camperas', ARRAY['Marron']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-jeans/campera-jeans-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-jeans/campera-jeans-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-jeans/campera-jeans-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-jeans/campera-jeans-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-jeans/campera-jeans-5.jpg']::text[], 'campera-jeans', 6),
  ('Campera rockera (biker)', 'Campera biker de cuero negro, con cierres y actitud rockera. El clasico infaltable que sube de nivel cualquier look.', 'Camperas', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-rockerita/campera-rockerita-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-rockerita/campera-rockerita-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-rockerita/campera-rockerita-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-rockerita/campera-rockerita-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-rockerita/campera-rockerita-5.jpg']::text[], 'campera-rockerita', 7),
  ('Campera Espana (biker)', 'Campera de cuero negro con cierre asimetrico y detalles biker. Estructurada, con caracter, para usar todo el ano.', 'Camperas', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-espana/campera-espana-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-espana/campera-espana-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-espana/campera-espana-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-espana/campera-espana-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-espana/campera-espana-5.jpg']::text[], 'campera-espana', 8),
  ('Campera Tina (oversized)', 'Campera oversized de cuero cognac, corte cropped y mangas globo con punos de hebilla. Volumen y color calido para un look moderno.', 'Camperas', ARRAY['Cognac']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-tina/campera-tina-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-tina/campera-tina-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-tina/campera-tina-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-tina/campera-tina-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/campera-tina/campera-tina-5.jpg']::text[], 'campera-tina', 9),
  ('Blazer de cuero', 'Blazer de cuero negro, sastreria con onda. Estiliza la silueta y transforma un jean + remera en un outfit completo.', 'Blazers', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/blazer/blazer-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/blazer/blazer-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/blazer/blazer-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/blazer/blazer-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/blazer/blazer-5.jpg']::text[], 'blazer', 10),
  ('Camisa de gamuza', 'Camisa de gamuza en tono caramelo, suave al tacto, con bolsillos de pecho y una caida perfecta. Se lleva como camisa o como sobrecamisa.', 'Camisas', ARRAY['Caramelo']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-gamuza/camisa-gamuza-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-gamuza/camisa-gamuza-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-gamuza/camisa-gamuza-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-gamuza/camisa-gamuza-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-gamuza/camisa-gamuza-5.jpg']::text[], 'camisa-gamuza', 11),
  ('Camisa de cuero', 'Camisa de cuero negro de textura marcada. Se usa abierta o cerrada y aporta textura y presencia a cualquier base.', 'Camisas', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-folds/camisa-folds-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-folds/camisa-folds-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-folds/camisa-folds-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-folds/camisa-folds-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/camisa-folds/camisa-folds-5.jpg']::text[], 'camisa-folds', 12),
  ('Falda de cuero con botones', 'Falda midi de cuero con botonadura frontal y tajo. Largo elegante y silueta que estiliza; se luce con botas o con zapatillas.', 'Faldas', ARRAY['Bordo']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/falda-botones/falda-botones-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/falda-botones/falda-botones-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/falda-botones/falda-botones-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/falda-botones/falda-botones-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/falda-botones/falda-botones-5.jpg']::text[], 'falda-botones', 13),
  ('Pantalon de cuero wide-leg', 'Pantalon de cuero negro de pierna ancha (wide-leg), con cintura comoda y caida fluida. Elegancia sin esfuerzo.', 'Pantalones', ARRAY['Negro']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/pantalon/pantalon-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/pantalon/pantalon-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/pantalon/pantalon-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/pantalon/pantalon-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/pantalon/pantalon-5.jpg']::text[], 'pantalon', 14),
  ('Conjunto print reptil', 'Conjunto de cuero con print reptil: campera + pantalon wide-leg. Se usan juntos para un look total o por separado como piezas statement.', 'Conjuntos', ARRAY['Estampado reptil']::text[], ARRAY['S','M','L','XL']::text[], ARRAY['https://loekemeyer.github.io/Ventas-MV/assets/productos/conjunto-reptil/conjunto-reptil-1.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/conjunto-reptil/conjunto-reptil-2.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/conjunto-reptil/conjunto-reptil-3.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/conjunto-reptil/conjunto-reptil-4.jpg','https://loekemeyer.github.io/Ventas-MV/assets/productos/conjunto-reptil/conjunto-reptil-5.jpg']::text[], 'conjunto-reptil', 15)
) as v(nombre, descripcion, categoria, colores, talles, imagenes, slug, orden)
where not exists (
  select 1 from productos p where lower(p.nombre) = lower(v.nombre)
);

-- Ver lo que se cargo (deberian aparecer como activo=false):
-- select nombre, categoria, precio, activo, array_length(imagenes,1) as fotos from productos order by orden;
